# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Hungarian Algorithm - Total Cost Calculation
#' @description
#' Computes the total minimum cost of an assignment using the Hungarian algorithm
#' (also known as the Kuhn-Munkres algorithm). This version returns only the cost,
#' not the specific assignment.
#'
#' @param matrix A square numeric matrix representing the cost of assigning row \code{i} to column \code{j}.
#'
#' @return A single numeric value representing the total minimal assignment cost.
#'
#' @examples
#' cost_matrix <- matrix(c(5, 9, 1, 3, 2, 4, 8, 7, 6), nrow = 3)
#' hungarian_cost_cpp(cost_matrix)
#'
#' @export
hungarian_cost_cpp <- function(matrix) {
    .Call(`_StudentProjectAllocation_hungarian_cost_cpp`, matrix)
}

#' @title Hungarian Algorithm - Optimal Assignment
#' @description
#' Solves the assignment problem using the Hungarian algorithm and returns
#' the optimal assignment vector that minimizes the total cost.
#'
#' The algorithm finds a perfect matching in a bipartite graph with minimum total weight,
#' based on the input cost matrix.
#'
#' @param cost A square numeric matrix representing the cost of assigning row \code{i} to column \code{j}.
#'
#' @return An integer vector of length \code{n}, where the \code{i}-th element indicates
#' the column assigned to row \code{i}.
#'
#' @examples
#' cost_matrix <- matrix(c(5, 9, 1, 3, 2, 4, 8, 7, 6), nrow = 3)
#' hungarian_assignment_cpp(cost_matrix)
#'
#' @export
hungarian_assignment_cpp <- function(cost) {
    .Call(`_StudentProjectAllocation_hungarian_assignment_cpp`, cost)
}

#' @title Genetic Algorithm for Assignment Problem
#' @description
#' This function implements a genetic algorithm to solve an assignment problem
#' using a cost matrix. It returns the optimal assignment found (minimizing the
#' total cost) and its corresponding cost.
#'
#' The algorithm works by generating an initial population of random permutations,
#' selecting the best individuals each generation, and producing new ones via
#' crossover and mutation.
#'
#' @param costMatrix A square numeric matrix \code{n x n}, representing the cost
#' of assigning item \code{i} to position \code{j}.
#' @param popSize An integer specifying the number of individuals (assignments) in each generation. Default is 100.
#' @param generations An integer giving the number of generations to run the genetic algorithm. Default is 500.
#' @param mutationRate A numeric value (between 0 and 1) giving the probability of mutation. Default is 0.1.
#'
#' @return A \code{list} with the following elements:
#' \itemize{
#'   \item \code{cost}: The total cost (fitness) of the best assignment found.
#'   \item \code{assignment}: An integer vector representing the assignment.
#'   Each position i in the vector corresponds to student i, 
#'   and the value at that position indicates the assigned project. 
#' }
#'
#' @examples
#' set.seed(123)
#' cost_matrix <- matrix(sample(1:100, 36, replace = TRUE), nrow = 6)
#' result <- genetic_algorithm_cpp(cost_matrix)
#' result$cost
#' result$assignment
#'
#' @export
genetic_algorithm_cpp <- function(costMatrix, popSize = 100L, generations = 500L, mutationRate = 0.1) {
    .Call(`_StudentProjectAllocation_genetic_algorithm_cpp`, costMatrix, popSize, generations, mutationRate)
}

